cmake_minimum_required(VERSION 3.15.0)

function(slimenano_arch ARCH)
    if(CMAKE_SIZEOF_VOID_P EQUAL 4)
        set(${ARCH} "x86" PARENT_SCOPE)
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(${ARCH} "x64" PARENT_SCOPE)
    elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64")
        set(${ARCH} "x64" PARENT_SCOPE)
    elseif(CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "i386" OR CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86")
        set(${ARCH} "x86" PARENT_SCOPE)
    else()
        set(${ARCH} "unknown" PARENT_SCOPE)
    endif()
endfunction()